services:
  db:
    image: postgres:17-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/product.sql:/docker-entrypoint-initdb.d/product.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: